### ISSUE TITLE
提供一个压缩包，把python虚拟环境打包进去

### ISSUE THREAD

**Issue by peiyangL** [rxrw/daily_morning#127]
今天进群看了下，觉得github actions的配置很容易出问题，不容易debug，并且不稳定。

而大多数人其实只是想图个新鲜体验一下这个功能，截个图之类的。可以考虑提供一个把python打包进去的压缩包（针对windows用户），改了config之后在自己电脑可以直接跑。这个方案主要问题还是电脑会关机，但是可以比较好地满足大家截图的需求。

此外这个方案还可以提供给小白：我独立跑了代码的新鲜感。

不成熟的想法，仅供参考。我手头目前也没windows，不太方便帮忙。有兴趣的同学可以实现下

**Comment by rxrw** [comment]
啊这个不是有一个网友做了吗。。自己打包了个 exe，改 config 的

**Comment by peiyangL** [comment]
是么，之前没注意别人搞得。那没事了，哈哈
