### ISSUE TITLE
微信端返回错误：appid missing rid: 6312cfb8-0d23d03a-67a424e5。错误代码：41002 Error: Process completed with exit code 246.

### ISSUE THREAD

**Issue by kunshanZhang** [rxrw/daily_morning#145]
微信端返回错误：appid missing rid: 6312cfb8-0d23d03a-67a424e5。错误代码：41002
Error: Process completed with exit code 246.

**Comment by whiteyear** [comment]
往上看几行应该还有一句这个报错ERRMSG=invalid appsecret.这个说的是actions里的APPsecret和微信公众平台的APPsecret不一致，把旧的删掉，然后刷新微信公众平台，把最新的APPsecret放到新的里面就好了

**Comment by kunshanZhang** [comment]
Successfully installed certifi-2022.6.15 cffi-1.15.1 charset-normalizer-2.1.0 cryptography-37.0.4 idna-3.3 optionaldict-0.1.2 pycparser-2.21 python-dateutil-2.8.2 requests-2.28.1 six-1.16.0 urllib3-1.26.11 wechatpy-1.8.18 xmltodict-0.13.0
app_sercet 
user_ids ['***']
***
微信端返回错误：appid missing rid: 631893f9-0996e9c8-4f017378。错误代码：41002
Error: Process completed with exit code 246.

好像不是这个问题

**Comment by rxrw** [comment]
是说你的 appid 填错了

**Comment by kunshanZhang** [comment]
解决了，谢谢啦
