### ISSUE TITLE
能不能增加一个函数功能：距离下一次见面的时间

### ISSUE THREAD

**Issue by Berlinss** [rxrw/daily_morning#22]
函数的功能是：输入一个下一次见面的时间，比如10-1
自动计算出距离那天的时间并显示出来，函数我会写，主要是怎么显示我不会

**Comment by beichen123-hub** [comment]
python倒计时，你可以参考他的main.py代码然后上网复制个倒计时然后自己写一个参数放进去 然后在actions工作流里也要加入那个参数，然后再setting里面也要新加参数

**Comment by wangzp0828** [comment]
![88DF0D08583520D471BE29D1EDC3920B](https://user-images.githubusercontent.com/111725348/186082389-605b24ab-9e34-41b0-94d2-cf36939ab40d.jpg)
我写了个这样的，剩下的灯一两天能不能自己执行了
