### ISSUE TITLE
Error: Process completed with exit code 1.这是什么问题啊。。

### ISSUE THREAD

**Issue by TheOrient22** [rxrw/daily_morning#27]
Error: Process completed with exit code 1.
能解答一下吗，按部就班怎么还是出了问题。。。

**Comment by Wenqing-hub** [comment]
@TheOrient22  well，I have the same error issue.

def get_weather():
  url = "http://autodev.openspeech.cn/csp/api/v2.1/weather?openId=aiuicus&clientType=android&sign=android&city=" + city
  res = requests.get(url).json()
  weather = res['data']['list'][0]
  return weather['weather'], math.floor(weather['temp'])

wea, temperature = get_weather()

issue log:
wea, temperature = get_weather()
  File "/home/runner/work/daily_moring/daily_moring/./main.py", line 24, in get_weather
    weather = res['data']['list'][0]



IndexError: list index out of range
Error: Process completed with exit code [1](https://github.com/Wenqing-hub/daily_moring/runs/7951168946?check_suite_focus=true#step:8:1).

**Comment by Wenqing-hub** [comment]
@TheOrient22 

https://github.com/rxrw/daily_morning/issues/14

**Comment by fromann** [comment]
> Error: Process completed with exit code 1. 能解答一下吗，按部就班怎么还是出了问题。。。

有没有详细的报错log，单看这一句看不出为什么

**Comment by Wenqing-hub** [comment]
> 

@fromann 你可以看我的这个log，貌似是输入的某些格式与预设的mismatch，但我也没找到是哪里的问题

**Comment by TheOrient22** [comment]
@fromann 

Run pip install -r ./requirements.txt && python ./main.py
Collecting certifi==2022.6.15
  Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.2/160.2 kB 7.3 MB/s eta 0:00:00
Collecting cffi==1.15.1
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux20[14](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:15)_x86_64.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 kB 10.8 MB/s eta 0:00:00
Collecting charset-normalizer==2.1.0
  Downloading charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
Collecting cryptography==37.0.4
  Downloading cryptography-37.0.4-cp36-abi3-manylinux_2_24_x86_64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 54.8 MB/s eta 0:00:00
Collecting idna==3.3
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB [15](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:16).3 MB/s eta 0:00:00
Collecting optionaldict==0.1.2
  Downloading optionaldict-0.1.2-py2.py3-none-any.whl (3.8 kB)
Collecting pycparser==2.21
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 27.1 MB/s eta 0:00:00
Collecting python-dateutil==2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 44.3 MB/s eta 0:00:00
Collecting requests==2.28.1
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 15.0 MB/s eta 0:00:00
Collecting six==1.[16](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:17).0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3==1.26.11
  Downloading urllib3-1.26.11-py2.py3-none-any.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 30.4 MB/s eta 0:00:00
Collecting wechatpy==1.8.[18](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:19)
  Downloading wechatpy-1.8.18-py2.py3-none-any.whl (159 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.2/159.2 kB 36.9 MB/s eta 0:00:00
Collecting xmltodict==0.13.0
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Installing collected packages: optionaldict, xmltodict, urllib3, six, pycparser, idna, charset-normalizer, certifi, requests, python-dateutil, cffi, wechatpy, cryptography
Successfully installed certifi-[20](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:21)22.6.15 cffi-1.15.1 charset-normalizer-2.1.0 cryptography-37.0.4 idna-3.3 optionaldict-0.1.2 pycparser-2.[21](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:22) python-dateutil-2.8.2 requests-2.28.1 six-1.16.0 urllib3-1.[26](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:27).11 wechatpy-1.8.18 xmltodict-0.13.0
Traceback (most recent call last):
  File "/home/runner/work/Morning/Morning/./main.py", line 51, in <module>
    data = {"weather":{"value":wea},"temperature":{"value":temperature},"love_days":{"value":get_count()},"birthday_left":{"value":get_birthday()},"words":{"value":get_words(), "color":get_random_color()}}
  File "/home/runner/work/Morning/Morning/./main.py", line [28](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:29), in get_count
    delta = today - datetime.strptime(start_date, "%Y-%m-%d")
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line [34](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:35)9, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'
Error: Process completed with exit code 1.


这是全部的报错log

**Comment by Wenqing-hub** [comment]
@TheOrient22 你时间的format 与预设的一致吗？%Y-%m-%d

**Comment by Wenqing-hub** [comment]
@fromann issue log: https://github.com/Wenqing-hub/daily_moring/runs/7951650596?check_suite_focus=true

**Comment by fromann** [comment]
> @fromann
> 
> Run pip install -r ./requirements.txt && python ./main.py Collecting certifi==2022.6.15 Downloading certifi-2022.6.15-py3-none-any.whl (160 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.2/160.2 kB 7.3 MB/s eta 0:00:00 Collecting cffi==1.15.1 Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux20[14](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:15)_x86_64.whl (441 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 kB 10.8 MB/s eta 0:00:00 Collecting charset-normalizer==2.1.0 Downloading charset_normalizer-2.1.0-py3-none-any.whl (39 kB) Collecting cryptography==37.0.4 Downloading cryptography-37.0.4-cp36-abi3-manylinux_2_24_x86_64.whl (4.1 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 54.8 MB/s eta 0:00:00 Collecting idna==3.3 Downloading idna-3.3-py3-none-any.whl (61 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB [15](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:16).3 MB/s eta 0:00:00 Collecting optionaldict==0.1.2 Downloading optionaldict-0.1.2-py2.py3-none-any.whl (3.8 kB) Collecting pycparser==2.21 Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 27.1 MB/s eta 0:00:00 Collecting python-dateutil==2.8.2 Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 44.3 MB/s eta 0:00:00 Collecting requests==2.28.1 Downloading requests-2.28.1-py3-none-any.whl (62 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 15.0 MB/s eta 0:00:00 Collecting six==1.[16](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:17).0 Downloading six-1.16.0-py2.py3-none-any.whl (11 kB) Collecting urllib3==1.26.11 Downloading urllib3-1.26.11-py2.py3-none-any.whl (139 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 30.4 MB/s eta 0:00:00 Collecting wechatpy==1.8.[18](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:19) Downloading wechatpy-1.8.18-py2.py3-none-any.whl (159 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.2/159.2 kB 36.9 MB/s eta 0:00:00 Collecting xmltodict==0.13.0 Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB) Installing collected packages: optionaldict, xmltodict, urllib3, six, pycparser, idna, charset-normalizer, certifi, requests, python-dateutil, cffi, wechatpy, cryptography Successfully installed certifi-[20](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:21)22.6.15 cffi-1.15.1 charset-normalizer-2.1.0 cryptography-37.0.4 idna-3.3 optionaldict-0.1.2 pycparser-2.[21](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:22) python-dateutil-2.8.2 requests-2.28.1 six-1.16.0 urllib3-1.[26](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:27).11 wechatpy-1.8.18 xmltodict-0.13.0 Traceback (most recent call last): File "/home/runner/work/Morning/Morning/./main.py", line 51, in data = {"weather":{"value":wea},"temperature":{"value":temperature},"love_days":{"value":get_count()},"birthday_left":{"value":get_birthday()},"words":{"value":get_words(), "color":get_random_color()}} File "/home/runner/work/Morning/Morning/./main.py", line [28](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:29), in get_count delta = today - datetime.strptime(start_date, "%Y-%m-%d") File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/_strptime.py", line [34](https://github.com/TheOrient22/Morning/runs/7949948791?check_suite_focus=true#step:4:35)9, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data '' does not match format '%Y-%m-%d' Error: Process completed with exit code 1.
> 
> 这是全部的报错log

你看看你是不是吧START_DAT**E** 写成START_DAT**A**了

**Comment by fromann** [comment]
> @fromann issue log: https://github.com/Wenqing-hub/daily_moring/runs/7951650596?check_suite_focus=true

这个好多报错，我不知道你Secrets/Action 值设置对了没

**Comment by TheOrient22** [comment]
@fromann 反复确定以及肯定secrets这些值都是正确的，因为我重复写了好多次（一直怀疑这里有问题）

**Comment by Wenqing-hub** [comment]
> > @fromann issue log: https://github.com/Wenqing-hub/daily_moring/runs/7951650596?check_suite_focus=true
> 
> 这个好多报错，我不知道你Secrets/Action 值设置对了没

Repository secrets 这几个都是对着直接Copy过来的呀，检查了一下也没有错

wechatpy.exceptions.WeChatClientException: Error code: 40125, message: invalid appsecret rid: 6303767d-5ec792b7-06d0e210
这行error log 是不是与APP_ID 这个变量有关 貌似与wechat的链接就是fail的

**Comment by Wenqing-hub** [comment]
> > > @fromann issue log: https://github.com/Wenqing-hub/daily_moring/runs/7951650596?check_suite_focus=true
> > 
> > 
> > 这个好多报错，我不知道你Secrets/Action 值设置对了没
> 
> Repository secrets 这几个都是对着直接Copy过来的呀，检查了一下也没有错
> 
> wechatpy.exceptions.WeChatClientException: Error code: 40125, message: invalid appsecret rid: 6303767d-5ec792b7-06d0e210 这行error log 是不是与APP_ID 这个变量有关 貌似与wechat的链接就是fail的

@fromann  我找到问题了，微信那边测试接口没有打开 现在是success  多谢😊

**Comment by fromann** [comment]
> > > > @fromann issue log: https://github.com/Wenqing-hub/daily_moring/runs/7951650596?check_suite_focus=true
> > > 
> > > 
> > > 这个好多报错，我不知道你Secrets/Action 值设置对了没
> > 
> > 
> > Repository secrets 这几个都是对着直接Copy过来的呀，检查了一下也没有错
> > wechatpy.exceptions.WeChatClientException: Error code: 40125, message: invalid appsecret rid: 6303767d-5ec792b7-06d0e210 这行error log 是不是与APP_ID 这个变量有关 貌似与wechat的链接就是fail的
> 
> @fromann 我找到问题了，微信那边测试接口没有打开 现在是success 多谢😊

<html>
<body>


40125 | 无效的appsecret
-- | --



</body>
</html>


你的测试公众号密码好像错了

**Comment by Wenqing-hub** [comment]
> > > > > @fromann issue log: https://github.com/Wenqing-hub/daily_moring/runs/7951650596?check_suite_focus=true
> > > > 
> > > > 
> > > > 这个好多报错，我不知道你Secrets/Action 值设置对了没
> > > 
> > > 
> > > Repository secrets 这几个都是对着直接Copy过来的呀，检查了一下也没有错
> > > wechatpy.exceptions.WeChatClientException: Error code: 40125, message: invalid appsecret rid: 6303767d-5ec792b7-06d0e210 这行error log 是不是与APP_ID 这个变量有关 貌似与wechat的链接就是fail的
> > 
> > 
> > @fromann 我找到问题了，微信那边测试接口没有打开 现在是success 多谢😊
> 
> 40125	无效的appsecret
> 你的测试公众号密码好像错了

yeah  我update了，现在可以了 多谢

**Comment by mumumie** [comment]
![image](https://user-images.githubusercontent.com/26733591/185952732-7ea8370e-9044-4883-ab98-57e826311bd8.png)
微信接口配置信息必须填写吗

**Comment by mumumie** [comment]
> > > > > > @fromann issue log: https://github.com/Wenqing-hub/daily_moring/runs/7951650596?check_suite_focus=true
> > > > > 
> > > > > 
> > > > > 这个好多报错，我不知道你Secrets/Action 值设置对了没
> > > > 
> > > > 
> > > > Repository secrets 这几个都是对着直接Copy过来的呀，检查了一下也没有错
> > > > wechatpy.exceptions.WeChatClientException: Error code: 40125, message: invalid appsecret rid: 6303767d-5ec792b7-06d0e210 这行error log 是不是与APP_ID 这个变量有关 貌似与wechat的链接就是fail的
> > > 
> > > 
> > > @fromann 我找到问题了，微信那边测试接口没有打开 现在是success 多谢😊
> > 
> > 
> > 40125	无效的appsecret
> > 你的测试公众号密码好像错了
> 
> yeah 我update了，现在可以了 多谢

wechatpy.exceptions.WeChatClientException: Error code: 40125, message: invalid appsecret rid: 63039998-24e9d07d-33af2a1a
Error: Process completed with exit code 1.
这里微信要开启啥  我也报这个错

**Comment by JxxJoh** [comment]
> ![image](https://user-images.githubusercontent.com/26733591/185952732-7ea8370e-9044-4883-ab98-57e826311bd8.png) 微信接口配置信息必须填写吗

这个需要填写什么 我也不清楚 你弄好了吗 告诉一下 谢谢兄弟
