### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by a152697354625** [rxrw/daily_morning#30]
Successfully installed certifi-2022.6.15 cffi-1.15.1 charset-normalizer-2.1.0 cryptography-37.0.4 idna-3.3 optionaldict-0.1.2 pycparser-2.21 python-dateutil-2.8.2 requests-2.28.1 six-1.16.0 urllib3-1.26.11 wechatpy-1.8.18 xmltodict-0.13.0
Traceback (most recent call last):
  File "/home/runner/work/c/c/./main.py", line 10, in <module>
    start_date = os.environ['2020-11-22']
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: '2020-11-22'
Error: Process completed with exit code 1.

**Comment by gutongww** [comment]
你的Actions secrets里设置的的START_DATE的值是2020-11-22

所以应该是start_date = os.environ['START_DATE']
