### ISSUE TITLE
多个接收人怎么设置呢

### ISSUE THREAD

**Issue by zhufacai** [rxrw/daily_morning#33]

**Comment by gutongww** [comment]
新建一行放入接受人id就好了

**Comment by zhufacai** [comment]
> 新建一行放入接受人id就好了
就是在user_id里面每行写一个接收人id吗

**Comment by gutongww** [comment]
> > 新建一行放入接受人id就好了
> > 就是在user_id里面每行写一个接收人id吗

对 

USER_ID:
id1xxxxxx
id2xxxxxx

这样就行了

**Comment by zhufacai** [comment]
> > > 新建一行放入接受人id就好了
> > > 就是在user_id里面每行写一个接收人id吗
> 
> 对
> 
> USER_ID: id1xxxxxx id2xxxxxx
> 
> 这样就行了

可以的，感谢😘
