### ISSUE TITLE
为啥没有自动触发的

### ISSUE THREAD

**Issue by wangzp0828** [rxrw/daily_morning#35]
![image](https://user-images.githubusercontent.com/111725348/186051640-9d5a6be9-3be4-4cf4-9a6e-d6270c476f86.png)
为啥没有自动触发的

**Comment by wangzp0828** [comment]
****
都改成5分钟触发了，是我加参数了吗

**Comment by wangzp0828** [comment]
![image](https://user-images.githubusercontent.com/111725348/186056138-9ea0eff4-bbb8-4c08-8b5f-cc575d6135a6.png)
都改成5分钟触发了，是我加参数了吗

**Comment by fromann** [comment]
我的今天早上也没有自动触发

**Comment by monyyn** [comment]
我的今早也没有触发

**Comment by rxrw** [comment]
五分钟。。github可能把你封了吧。。你看看有没有邮件

**Comment by wangzp0828** [comment]
> 

没有邮件，就是之前早上没有发送我才定成5分钟一次看看有没有。。。
