### ISSUE TITLE
推送时间一直在变

### ISSUE THREAD

**Issue by min132097** [rxrw/daily_morning#4]
你好，我将代码拉取下来一点都没改，推送时间分别为：

1.  2022/08/09 09:51
2.  2022/08/10 09:37
3.  2022/08/11 09:39
4.  2022/08/12 09:42
5.  2022/08/13 09:27
6.  2022/08/14 09:50
7.  2022/08/15 09:53

请问为什么会出现这种现象呢？

**Comment by rxrw** [comment]
GitHub 的任务有延迟
