### ISSUE TITLE
可以帮忙看一下这个报错嘛 纯小白

### ISSUE THREAD

**Issue by tangxinbo28** [rxrw/daily_morning#7]
wechatpy.exceptions.WeChatClientException: Error code: 40003, message: invalid openid rid: 630212bf-3db44efc-3cc33c93
Error: Process completed with exit code 1.
手动版本的exe上面已经做好了 就是这个想自动定时发送的一直有问题可以帮忙看一下嘛 谢谢

**Comment by nanyanglk** [comment]
微信公众平台有关于返回码说明

**Comment by rxrw** [comment]
用户 id 错误
