### ISSUE TITLE
增加服务器运行版本与定时触发功能

### ISSUE THREAD

**Issue by peiyangL** [rxrw/daily_morning#82]
添加一个分支提供给有服务器的小伙伴，完善配置样例，并加上定时发送功能

如果有需要这部分我可以找时间写下。

**Comment by rxrw** [comment]
可以的啊，建议用 docker 实现

用 python 又涉及安装 pip virtualenv crontab 了

**Comment by peiyangL** [comment]
都自己有设备了，环境问题这些就自行解决吧，hhh

**Comment by peiyangL** [comment]
@rxrw 这是里希望新建一个分支还是直接在master上做改动？

如果新建分支之后master上的一些功能更新还需要手工同步。

**Comment by peiyangL** [comment]
PR: https://github.com/rxrw/daily_morning/pull/111
