### ISSUE TITLE
增加了阴历的生日计算哦

### ISSUE THREAD

**Issue by whadmin1666** [rxrw/daily_morning#88]

**Comment by onvz** [comment]
问下阴历怎么填写? "五月二十 "这样吗?

**Comment by whadmin1666** [comment]
> 问下阴历怎么填写? "五月二十 "这样吗?

还是正常填写，就"09-26"这样就行

**Comment by onvz** [comment]
那,代码里面要做什么设置吗?  我是完全按照说明里面照猫画虎的,可以说明一下吗? 感谢

**Comment by whadmin1666** [comment]
不用设置啥啊



发自我的小米
在 onvz ***@***.***>，2022年8月27日 21:53写道：

那,代码里面要做什么设置吗? 我是完全按照说明里面照猫画虎的,可以说明一下吗? 感谢

**Comment by rxrw** [comment]
duplicate as #94
