### ISSUE TITLE
这个写的很好，有个问题请教您。

### ISSUE THREAD

**Issue by zhangdong1107** [rxrw/daily_morning#9]
请问，每天8点循环是如何实现的？我在main.py里并未发现循环语句。谢谢回复

**Comment by nanyanglk** [comment]
不需要写循环 放服务器写定时任务就行

**Comment by zhangdong1107** [comment]
谢谢回复。请问，您目前这个程序已经实现每天8点发送了吗。在服务器写定时任务，是如何操作呢。期待您的回复。

**Comment by nanyanglk** [comment]
这个项目不是我提交的，我的方法是linux写crontab

**Comment by zhangdong1107** [comment]
谢谢回复。linux写crontab，直接就可以云端了嘛，这么神奇。

**Comment by rxrw** [comment]
@nanyanglk 的方法是自己的服务器部署，这里靠白嫖，在 .github/workflow/main.yml 里面设置
